### ISSUE TITLE
bind before start race condition

### ISSUE THREAD

**Issue by minrk** [RantyDave/zmq_ipc#1]
Something might be a bit confused, here. This code works without `set_start_method`. On some libzmq versions the bind,connect order can matter, and this code as written would expect bind to happen after connect, assuming spawning the Process is fast. If setting the start method to 'spawn' really does help, I expect that it is doing so by making the spawn slow enough to be more likely that connect happens after bind.

If you bind the server socket before spawning the subprocesses, I think you'll be okay. This doesn't seem to be an issue for more recent versions of libzmq (in my testing, at least).

**Comment by RantyDave** [comment]
Oh it works *now*, doesn't it! I can only imagine something was borked on the other system. Bugger. I'm going to close the bug and nuke the project. Thank you for drawing my attention to this.
